name = "sunportparking-com-v1"
compatibility_date = "2026-07-06"
preview_urls = false
workers_dev = false

[assets]
directory = "./dist"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true
